### ISSUE TITLE
group.queue.spotifyuri return error 800 (Command not supported or not a coordinator)

### ISSUE THREAD

**Issue by thomasoggier** [hklages/node-red-contrib-sonos-plus#311]
### Description
Each time I try to add spotify playlist to my sonos player I get this error:

group.queue.urispotify:Sonos error on AddURIToQueue UPnPError 800 (Command not supported or not a coordinator) :: Details: {"stack":"SonosError: Sonos error on AddURIToQueue UPnPError 800 (Command not supported or not a coordinator)\n    at AVTransportService.handleErrorResponse (/config/node_modules/@svrooij/sonos/lib/services/base-service.js:227:23)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AVTransportService.handleRequestAndParseResponse (/config/node_modules/@svrooij/sonos/lib/services/base-service.js:199:15)\n    at SonosDevice.AddUriToQueue (/config/node_modules/@svrooij/sonos/lib/sonos-device.js:95:16)\n    at Object.groupQueueUriFromSpotify [as group.queue.urispotify] (/config/node_modules/node-red-contrib-sonos-plus/src/sonos-universal.js:1854:20)","message":"Sonos error on AddURIToQueue UPnPError 800 (Command not supported or not a coordinator)","Action":"AddURIToQueue","FaultCode":"s:Client","Fault":"UPnPError","UpnpErrorCode":800,"Up...

The player's configuration should be correct because another node start tunein radio on the same player. I've also try with the node group.queue.uri, same issue

### What node/command (topic)/state (payload)

node: Universal
command: group.queue.spotifyuri
state: Error 800 (Command not supported or not a coordinator)

### In case of a bug: Are you able to reproduce the error

[{"id":"17d6e1d4697c80b5","type":"tab","label":"Flux 2","disabled":false,"info":"","env":[]},{"id":"1a03031603c8822b","type":"inject","z":"17d6e1d4697c80b5","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":130,"y":160,"wires":[["b3dee0519d3554d7"]]},{"id":"5ba074088b8a70e2","type":"sonos-universal","z":"17d6e1d4697c80b5","confignode":"64831d51.645b54","command":"group.queue.urispotify","state":"spotify:playlist:37i9dQZF1E4FFFFcrWLjUk","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":360,"y":100,"wires":[[]]},{"id":"b3dee0519d3554d7","type":"sonos-universal","z":"17d6e1d4697c80b5","confignode":"64831d51.645b54","command":"group.queue.uri","state":"spotify:album:2bl3fqhASHS45oLpOD6Jiy","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":340,"y":160,"wires":[[]]},{"id":"b848633f6051fead","type":"sonos-universal","z":"17d6e1d4697c80b5","confignode":"64831d51.645b54","command":"group.play.tunein","state":"s58290","stateType":"str","avoidCheckPlayerAvailability":false,"name":"Radio","x":310,"y":40,"wires":[[]]},{"id":"6ef52a97847bbcbb","type":"inject","z":"17d6e1d4697c80b5","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":130,"y":100,"wires":[["5ba074088b8a70e2"]]},{"id":"4f71d752f6e2607a","type":"inject","z":"17d6e1d4697c80b5","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":130,"y":40,"wires":[["b848633f6051fead"]]},{"id":"64831d51.645b54","type":"sonos-config","name":"Bureau","serialnum":"5C-AA-FD-0A-99-DE:9","ipaddress":"192.168.1.55"}]

### Versions and Infrastructure

**what system: ** Raspberry Pi
**node-red-contrib-sonos-plus version:** 6.9.0
**Node-RED version:** 18.1.1
**NodeJS version:** ???

see: [https://flows.nodered.org/flow/a5c42641bf33dd0da9bfd4426a06950a]

**Comment by thomasoggier** [comment]
Looks solved by node-red update
