### ISSUE TITLE
insert_spotify_uri does not succeed

### ISSUE THREAD

**Issue by MeanderingCode** [hklages/node-red-contrib-sonos-plus#46]
The `insert_spotify_uri` function of the `Manage Queue` node is not working for me.

I always receive `statusCode 500 & upnpError 800`, and If i add a region (as string or int) I get no output, at all.

![image](https://user-images.githubusercontent.com/634399/80548118-f222db80-896e-11ea-8f33-77b60ffa5ff2.png)

```
[{"id":"e6f6a47e.7c47e8","type":"sonos-manage-queue","z":"c0a5d9cc.64ffa","confignode":"46c85ed3.238c3","name":"","x":580,"y":320,"wires":[["927fe29c.7ecfc8","e94515fe.af9c7"]]},{"id":"927fe29c.7ecfc8","type":"debug","z":"c0a5d9cc.64ffa","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":890,"y":300,"wires":[]},{"id":"24094cc6.396af4","type":"inject","z":"c0a5d9cc.64ffa","name":"Spotify playlist","topic":"spotify:user:spotify:playlist:MYPLAYLIST","payload":"insert_spotify_uri","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":330,"y":280,"wires":[["e6f6a47e.7c47e8"]]},{"id":"4c1cc045.327878","type":"inject","z":"c0a5d9cc.64ffa","name":"Spotify track","topic":"spotify:track:6yIHGmQLJxWAUZ1ZkENemN","payload":"insert_spotify_uri","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":330,"y":320,"wires":[["e6f6a47e.7c47e8"]]},{"id":"e493c721.c1bf2","type":"inject","z":"c0a5d9cc.64ffa","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":110,"y":360,"wires":[["ba49a4fe.d3142"]]},{"id":"ba49a4fe.d3142","type":"function","z":"c0a5d9cc.64ffa","name":"Spotify track with region","func":"\nreturn {\n    payload: \"insert_spotify_uri\",\n    topic: \"spotify:track:6yIHGmQLJxWAUZ1ZkENemN\",\n    region: 3079\n};","outputs":1,"noerr":0,"x":290,"y":360,"wires":[["e6f6a47e.7c47e8"]]},{"id":"e94515fe.af9c7","type":"function","z":"c0a5d9cc.64ffa","name":"console log","func":"node.log(JSON.stringify(msg))","outputs":0,"noerr":0,"x":910,"y":340,"wires":[]},{"id":"a75cf24e.5b0c48","type":"catch","z":"c0a5d9cc.64ffa","name":"","scope":null,"uncaught":false,"x":600,"y":280,"wires":[["e94515fe.af9c7","927fe29c.7ecfc8"]]},{"id":"46c85ed3.238c3","type":"sonos-config","z":"","name":"Sonos","serialnum":"XX:XX:XX:XX:XX","ipaddress":"127.0.0.1"}]
```
(Config blanked and private playlist ID changed to `MYPLAYLIST`)

Debug logs from injecting commands for playlist, track, and playlist with `region`, respectively:
```
[debug] [sonos-manage-queue:cc953fc3.411ee] node - msg received
[debug] [sonos-manage-queue:cc953fc3.411ee] using IP address of config node
[debug] [sonos-manage-queue:cc953fc3.411ee] Entering error handling from insert spotify uri.
[debug] [sonos-manage-queue:cc953fc3.411ee] node - msg received
[debug] [sonos-manage-queue:cc953fc3.411ee] using IP address of config node
[debug] [sonos-manage-queue:cc953fc3.411ee] Entering error handling from insert spotify uri.
[debug] [sonos-manage-queue:cc953fc3.411ee] node - msg received
[debug] [sonos-manage-queue:cc953fc3.411ee] using IP address of config node
```
Console log from `Catch → console log function` from injecting commands for playlist, track, and track with region, respectively:
```
[info] [function:console log] {"_msgid":"5febc6c4.6dd1a8","topic":"spotify:user:spotify:playlist:3Su4eYCErApmz6D4ReRlLz","payload":"insert_spotify_uri","error":{"message":"insert spotify uri - statusCode 500 & upnpError 800 :: Details: Lookup upnpError 800","source":{"id":"e6f6a47e.7c47e8","type":"sonos-manage-queue","count":1}}}
[info] [function:console log] {"_msgid":"be840a7c.1ad088","topic":"spotify:track:6yIHGmQLJxWAUZ1ZkENemN","payload":"insert_spotify_uri","error":{"message":"insert spotify uri - statusCode 500 & upnpError 800 :: Details: Lookup upnpError 800","source":{"id":"e6f6a47e.7c47e8","type":"sonos-manage-queue","count":1}}}
[info] [function:console log] {"payload":"insert_spotify_uri","topic":"spotify:track:6yIHGmQLJxWAUZ1ZkENemN","region":3079,"_msgid":"43833c58.76c654","error":{"message":"TypeError: msg.region.match is not a function","source":{"id":"e6f6a47e.7c47e8","type":"sonos-manage-queue","count":1},"stack":"TypeError: msg.region.match is not a function\n    at insertSpotifyUri (/data/node_modules/node-red-contrib-sonos-plus/src/sonos-manage-queue.js:227:22)\n    at processInputMsg (/data/node_modules/node-red-contrib-sonos-plus/src/sonos-manage-queue.js:112:7)\n    at SonosManageQueueNode._inputCallback (/data/node_modules/node-red-contrib-sonos-plus/src/sonos-manage-queue.js:49:9)\n    at SonosManageQueueNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:200:18)\n    at Immediate._onImmediate (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)"}}
```
Last log formatted for convenience:
```
{
    "payload":"insert_spotify_uri",
    "topic":"spotify:track:6yIHGmQLJxWAUZ1ZkENemN",
    "region":3079,
    "_msgid":"43833c58.76c654",
    "error":{
        "message":"TypeError: msg.region.match is not a function",
        "source":{
            "id":"e6f6a47e.7c47e8",
            "type":"sonos-manage-queue",
            "count":1
        },
        "stack":"TypeError: msg.region.match is not a function\n    at insertSpotifyUri (/data/node_modules/node-red-contrib-sonos-plus/src/sonos-manage-queue.js:227:22)\n    at processInputMsg (/data/node_modules/node-red-contrib-sonos-plus/src/sonos-manage-queue.js:112:7)\n    at SonosManageQueueNode._inputCallback (/data/node_modules/node-red-contrib-sonos-plus/src/sonos-manage-queue.js:49:9)\n    at SonosManageQueueNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:200:18)\n    at Immediate._onImmediate (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)"
    }
}
```
Stack when `region` is passed as a number:
```
TypeError: msg.region.match is not a function
    at insertSpotifyUri (/data/node_modules/node-red-contrib-sonos-plus/src/sonos-manage-queue.js:227:22)
    at processInputMsg (/data/node_modules/node-red-contrib-sonos-plus/src/sonos-manage-queue.js:112:7)
    at SonosManageQueueNode._inputCallback (/data/node_modules/node-red-contrib-sonos-plus/src/sonos-manage-queue.js:49:9)
    at SonosManageQueueNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:200:18)
    at Immediate._onImmediate (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```
Stack when `region` is passed as a string:
```
TypeError: sonosPlayer.setSpotifiyRegion is not a function
    at insertSpotifyUri (/data/node_modules/node-red-contrib-sonos-plus/src/sonos-manage-queue.js:228:21)
    at processInputMsg (/data/node_modules/node-red-contrib-sonos-plus/src/sonos-manage-queue.js:112:7)
    at SonosManageQueueNode._inputCallback (/data/node_modules/node-red-contrib-sonos-plus/src/sonos-manage-queue.js:49:9)
    at SonosManageQueueNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:200:18)
    at Immediate._onImmediate (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

I have tried many things in order to change the state of my Sonos while troubleshooting this, primarily `leave_group`, but many iterations of control and state (playing, flush_queue, stop, and others)

**Comment by hklages** [comment]
I just publish 3.1.0 with a lot of new commands. You can now access Sonos playlists in My Sonos, save your current queue to a Sonos playlist, play that list, etc. Even remove Sonos playlists. 
So if you are able to play your Spotify Album, playlist in the Sonos App, you can save the queue and reuse that with My Sonos. 

Anyway in the next days I will have a look at the spotify issue and you pull reqeust.
