### ISSUE TITLE
My Sonos Node - 'length' of undefined error

### ISSUE THREAD

**Issue by tsprivate** [hklages/node-red-contrib-sonos-plus#52]
I'm using your latest code and all works fine besides the My_Sonos_Node getting the following error

`get My Sonos items: Cannot read property 'length' of undefined :: Details: {"stack":"TypeError: Cannot read property 'length' of undefined\n    at Object.parseSonosPlaylistsResult (/home/pi/.node-red/node_modules/node-red-contrib-sonos-plus/src/Sonos-Commands.js:942:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Object.getAllSonosPlaylists (/home/pi/.node-red/node_modules/node-red-contrib-sonos-plus/src/Sonos-Commands.js:644:32)\n    at async getAllMySonosItemsV2 (/home/pi/.node-red/node_modules/node-red-contrib-sonos-plus/src/Sonos-Commands.js:625:32)","message":"Cannot read property 'length' of undefined"}`

thanks for any advise

**Comment by tsprivate** [comment]
Sorry, It is already raised as issue
