### ISSUE TITLE
Get Items in My Sonos Node: Error

### ISSUE THREAD

**Issue by Drahos-X** [hklages/node-red-contrib-sonos-plus#65]
I have just installed **node-red-contrib-sonos-plus** on my Raspberry Pi 4 and I like it very much. I have no problem with using **Universal Node** with my Sonos system, but I have troubles with **My Sonos Node**. I tried the flow from **Wiki: A.2 My Sonos Node** (updated s/n and IP), however I am getting errors even with "get.items" command (see the details below). All other commands end up with same errors. Could you help?

_"get My Sonos items: item.albumArt.startsWith is not a function :: Details: {"stack":"TypeError: item.albumArt.startsWith is not a function\n    at /home/pi/.node-red/node_modules/node-red-contrib-sonos-plus/src/Sonos-Commands.js:590:27\n    at Array.forEach (<anonymous>)\n    at getAllMySonosItemsV2 (/home/pi/.node-red/node_modules/node-red-contrib-sonos-plus/src/Sonos-Commands.js:585:17)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","message":"item.albumArt.startsWith is not a function"}"_

Node-RED version: v1.0.6
Node.js  version: v12.16.3

**Comment by hklages** [comment]
Hi. What node-red-contrib-sonos-plus version? The newest?

**Comment by Drahos-X** [comment]
node-red-contrib-sonos-plus 3.1.4

**Comment by hklages** [comment]
How many items (playlists, album, station, ... ) Did you add to the "My Sonos" tab in your SONOS app? What kind of items? TuneIn, Spotify?

**Comment by Drahos-X** [comment]
Radio Stations (#14) - Sonos Radio Station (new service), TuneIn Station, Apple Music Station, Sonos Radio Station
Playlists (#20)
Songs (#1)
Recently Played (#0)
Albums (#4)
Folders (#4) - NAS server folder locations

I can try whatever could help, just let me know.

**Comment by hklages** [comment]
Are you familiar with any text editor on your system? 

1. make backup/copy of Sonos-Commands.js

2. edit the file and restart NodeRED
Add the following line: 
`console.log('albumart >>' + JSON.stringify(item.albumArt))` 
to file 
`... node-red-contrib-sonos-plus\src\Sonos-Commands.js`

![albumart](https://user-images.githubusercontent.com/17273119/82840567-589a0b80-9ed3-11ea-9d48-3ec28126a02c.png)

3. Do a get_items an and have a look at the console
Last entry should be the one causing trouble.

It could be that the item is not a string (maybe array). So far I havent had that case.

**Comment by Drahos-X** [comment]
I checked as you proposed, even added log inside the loop - it crashes after processing all items in the Radio Stations section.
On my sonos app the playlists follow afterwards (see the picture).

I also deleted the last item in Radio Stations, but the result is the same.

This is the output:
-----------------------
DRAHOS **********************************
DRAHOS: albumart >>"https://d1uner0r1fcap8.cloudfront.net/image?w=60&image=https%3A%2F%2Fcdn-radiotime-logos.tunein.com%2Fs25683q.png&partnerId=tunein"
DRAHOS: albumart >>"https://d1uner0r1fcap8.cloudfront.net/image?w=60&image=https%3A%2F%2Fcdn-radiotime-logos.tunein.com%2Fs121791q.png&partnerId=tunein"
DRAHOS: albumart >>"https://d1uner0r1fcap8.cloudfront.net/image?w=60&image=https%3A%2F%2Fcdn-radiotime-logos.tunein.com%2Fs45178q.png&partnerId=tunein"
DRAHOS: albumart >>"http://d1i6vahw24eb07.cloudfront.net/s9596q.gif"
DRAHOS: albumart >>"https://d1uner0r1fcap8.cloudfront.net/image?w=60&image=https%3A%2F%2Fcdn-profiles.tunein.com%2Fs112499%2Fimages%2Flogoq.jpg%3Ft%3D151076&partnerId=tunein"
DRAHOS: albumart >>"https://d1uner0r1fcap8.cloudfront.net/image?w=60&image=https%3A%2F%2Fcdn-radiotime-logos.tunein.com%2Fs299567q.png&partnerId=tunein"
DRAHOS: albumart >>"https://d1uner0r1fcap8.cloudfront.net/image?w=60&image=https%3A%2F%2Fcdn-radiotime-logos.tunein.com%2Fs133037q.png&partnerId=tunein"
DRAHOS: albumart >>"http://cdn-radiotime-logos.tunein.com/s25006q.png"
DRAHOS: albumart >>"https://d1uner0r1fcap8.cloudfront.net/image?w=60&image=https%3A%2F%2Fcdn-radiotime-logos.tunein.com%2Fs54713q.png&partnerId=tunein"
DRAHOS: albumart >>"https://is4-ssl.mzstatic.com/image/thumb/Features111/v4/82/0d/c5/820dc565-4e65-ac17-3a58-d91895f73862/source/400x400cc.jpeg"
DRAHOS: albumart >>"https://d1uner0r1fcap8.cloudfront.net/image?w=60&image=https%3A%2F%2Fcdn-radiotime-logos.tunein.com%2Fs121790q.png&partnerId=tunein"
DRAHOS: albumart >>["/getaa?s=1&u=x-sonos-http%3asong%253a269244793.mp4%3fsid%3d204%26flags%3d8224%26sn%3d3","/getaa?s=1&u=x-sonos-http%3asong%253a521132852.mp4%3fsid%3d204%26flags%3d8224%26sn%3d3","/getaa?s=1&u=x-sonos-http%3asong%253a112026522.mp4%3fsid%3d204%26flags%3d8224%26sn%3d3","/getaa?s=1&u=x-sonos-http%3asong%253a1033602731.mp4%3fsid%3d204%26flags%3d8224%26sn%3d3"]
26 May 12:20:12 - [error] [sonos-manage-mysonos:My Sonos Menu] get My Sonos items: item.albumArt.startsWith is not a function :: Details: {"stack":"TypeError: item.albumArt.startsWith is not a function\n    at /home/pi/.node-red/node_modules/node-red-contrib-sonos-plus/src/Sonos-Commands.js:593:27\n    at Array.forEach (<anonymous>)\n    at getAllMySonosItemsV2 (/home/pi/.node-red/node_modules/node-red-contrib-sonos-plus/src/Sonos-Commands.js:586:17)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","message":"item.albumArt.startsWith is not a function”}



Best regards,
Drahos

**Comment by hklages** [comment]
It's the apple playlist or album. 
I will fix it tomorrow.
